### ISSUE TITLE
Privkey can't be saved to dir on Windows

### ISSUE THREAD

**Issue by livegnik** [identifi/identifi-lib#1]
I received the following error when trying to run the Identifi daemon on a Windows machine:

`Error: Command failed: openssl ecparam -genkey -noout -name secp256k1 -out C:\Users\User/.identifi/private.key`

It seems that this happens because of line 37 in keyutil.js:

`privKeyFile = datadir + '/private.key';`

**Comment by livegnik** [comment]
Wrong repo. Should've been posted under "identifi-cli", since it also goes for line 18, in `/identifi-cli/identifi`:

`var datadir = process.env.IDENTIFI_DATADIR || (osHomedir() + '/.identifi');`

**Comment by mmalmi** [comment]
Not using openSSL anymore :)
