### ISSUE TITLE
IPFS gateway fallback not working

### ISSUE THREAD

**Issue by danfinlay** [identifi/identifi-lib#3]
I guess the identify ipfs gateway isn't working, it's throwing a 502 for me.

Instead of falling back to one of the other gateways, this is causing a throw on `Index.load()`:

```
Error: Failed to load page, status code: 502
    at ClientRequest.<anonymous> (/Users/danfinlay/Documents/Development/identify-experiments/node_modules/merkle-btree/cjs/IPFSGatewayStorage.js:37:16)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
```

I put a log in, and the failing request is for the url `https://identi.fi/ipfs/QmPKegyJCy9CiZRJJbRQ37kxyLSi1C5Xh85KUEqLL4TbGW`.

Personally, I'd rather pass my own IPFS object to identifi than have it bother with fallback strategies of any sort. That would let me configure my own local ipfs client, be it js-ipfs or pointing at a gateway.

Full sample failing code:

```javascript
const identify = require('identifi-lib')

const { Index, Message, Identity, Attribute, Key, util } = identify

Index.load().then(async (inex) => { console.dir(index) }).catch(console.error)
```

**Comment by mmalmi** [comment]
Oh man, I don't get how I missed this issue despite working on the repo all the time 😬 Sorry! Thanks for testing anyways. I'm closing this since the lib has changed a lot and now indexes on GUN instead of IPFS.
